GO_BIN ?= go

PKG_NAME := fastly
VERSION := $(shell git describe --tags --always)
VERSION_SHORT := $(shell git describe --tags --always --abbrev=0 2>/dev/null || echo v0.0.0)
DOCS_PROVIDER_VERSION := $(subst v,,$(VERSION_SHORT))
BIN_DIR := $(CURDIR)/bin
BINARY := $(BIN_DIR)/terraform-provider-$(PKG_NAME)_$(VERSION)
OVERRIDES_FILE := $(BIN_DIR)/developer_overrides.tfrc

.PHONY: fmt build dev-overrides clean test-unit test-acc generate-docs validate-docs docs test-lifecycle-cdn test-lifecycle-compute test-lifecycle help

help:
	@echo "Available targets:"
	@echo "  make build                  - Format code and build provider binary"
	@echo "  make fmt                    - Format Go code"
	@echo "  make clean                  - Remove build artifacts"
	@echo "  make test-unit              - Run unit tests"
	@echo "  make test-acc               - Run acceptance tests without Go test caching (requires FASTLY_API_TOKEN)"
	@echo "                                Add KEYWORD=<word> to only run tests whose name contains <word>"
	@echo "  make test-lifecycle-cdn     - Run CDN lifecycle tests (requires FASTLY_API_TOKEN)"
	@echo "  make test-lifecycle-compute - Run Compute lifecycle tests (requires FASTLY_API_TOKEN)"
	@echo "  make test-lifecycle         - Run all lifecycle tests (requires FASTLY_API_TOKEN)"

fmt:
	@echo "==> Formatting Go code..."
	@$(GO_BIN) fmt ./...

build: fmt
	@echo "==> Building provider binary..."
	@mkdir -p $(BIN_DIR)
	@$(GO_BIN) build -ldflags="-X 'github.com/fastly/terraform-provider-fastly/internal/version.Version=$(VERSION)'" -o $(BINARY)
	@$(MAKE) --no-print-directory dev-overrides

dev-overrides:
	@echo "==> Generating Terraform CLI development overrides..."
	@sh -c "'$(CURDIR)/scripts/generate-dev-overrides.sh'"

clean:
	@echo "==> Cleaning build artifacts..."
	@rm -rf $(BIN_DIR)

test-unit:
	@echo "==> Running unit tests..."
	@$(GO_BIN) test ./internal/...

test-acc:
	@echo "==> Running acceptance tests..."
	@echo "    Note: This requires FASTLY_API_TOKEN to be set"
	@TF_ACC=1 $(GO_BIN) test -count=1 -v -timeout 30m ./internal/acceptance_tests -run 'TestAcc.*$(KEYWORD)'

generate-docs:
	@echo "==> Generating Terraform Registry documentation..."
	@$(GO_BIN) tool -modfile=tools/go.mod tfplugindocs generate --provider-name $(PKG_NAME)
	@find docs -name '*.md' -exec sed -i.bak '/^<!-- schema generated by tfplugindocs -->$$/d' {} +
	@find docs -name '*.bak' -delete

validate-docs:
	@echo "==> Validating Terraform Registry documentation..."
	@$(GO_BIN) tool -modfile=tools/go.mod tfplugindocs validate --provider-name $(PKG_NAME)

docs: generate-docs validate-docs

test-lifecycle-cdn:
	@echo "==> Running CDN lifecycle tests..."
	@echo "    Note: This requires FASTLY_API_TOKEN to be set"
	@./scripts/test-lifecycle-cdn/run.sh

test-lifecycle-compute:
	@echo "==> Running Compute lifecycle tests..."
	@echo "    Note: This requires FASTLY_API_TOKEN to be set"
	@./scripts/test-lifecycle-compute/run.sh

test-lifecycle: test-lifecycle-cdn test-lifecycle-compute
	@echo "==> All lifecycle tests completed"
