package fastly

import (
	"context"
	"encoding/json"
	"log"
	"strconv"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	"github.com/fastly/terraform-provider-fastly/fastly/hashcode"

	gofastly "github.com/fastly/go-fastly/v17/fastly"
	"github.com/fastly/go-fastly/v17/fastly/airuntimecontrol/v1/session"
)

func dataSourceFastlyAIRuntimeControlSessions() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceFastlyAIRuntimeControlSessionsRead,
		Schema: map[string]*schema.Schema{
			"from": {
				Type:             schema.TypeString,
				Optional:         true,
				Description:      "The inclusive start of the time range to retrieve session logs for, in RFC 3339 format.",
				ValidateDiagFunc: validation.ToDiagFunc(validation.IsRFC3339Time),
			},
			"key": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Filter the results by virtual key ID.",
			},
			"model": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Filter the results by AI model identifier.",
			},
			// The Terraform SDK reserves the field name "provider" on every
			// data source, so the API's `provider` filter is exposed as
			// `provider_name`.
			"provider_name": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Filter the results by AI model provider name.",
			},
			"sessions": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "The session logs matching the given filters.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"created_at": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Timestamp (UTC) of when the session was created.",
						},
						"id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The ID of the session.",
						},
						"input_tokens": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: "The total input tokens consumed by the session.",
						},
						"logs": {
							Type:      schema.TypeList,
							Computed:  true,
							Sensitive: !DisplaySensitiveFields,
							// Log entries contain the raw prompts and
							// completions exchanged with the AI provider.
							Description: "The request and response log entries for the session. Contains the raw data exchanged with the AI provider, which is persisted to Terraform state in plaintext.",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"attrs": {
										Type:        schema.TypeMap,
										Computed:    true,
										Description: "Additional attributes for the log entry. Values that are not strings are JSON encoded.",
										Elem:        &schema.Schema{Type: schema.TypeString},
									},
									"request": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "The raw request data.",
									},
									"response": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "The raw response data.",
									},
								},
							},
						},
						"model": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The AI model identifier.",
						},
						"output_tokens": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: "The total output tokens generated by the session.",
						},
						"provider": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The AI provider name.",
						},
						"requests": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: "The number of requests in the session.",
						},
						"updated_at": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Timestamp (UTC) of when the session was last updated.",
						},
						"virtual_key_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The ID of the virtual key used.",
						},
						"virtual_key_name": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The human-readable name of the virtual key used.",
						},
					},
				},
			},
			"to": {
				Type:             schema.TypeString,
				Optional:         true,
				Description:      "The inclusive end of the time range to retrieve session logs for, in RFC 3339 format. Defaults to now.",
				ValidateDiagFunc: validation.ToDiagFunc(validation.IsRFC3339Time),
			},
			"total": {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: "The total number of sessions returned.",
			},
		},
	}
}

func dataSourceFastlyAIRuntimeControlSessionsRead(ctx context.Context, d *schema.ResourceData, meta any) diag.Diagnostics {
	conn := meta.(*APIClient).conn

	log.Printf("[DEBUG] Reading AI Runtime Control sessions")

	i := session.ListInput{}
	if v, ok := d.GetOk("key"); ok {
		i.Key = gofastly.ToPointer(v.(string))
	}
	if v, ok := d.GetOk("provider_name"); ok {
		i.Provider = gofastly.ToPointer(v.(string))
	}
	if v, ok := d.GetOk("model"); ok {
		i.Model = gofastly.ToPointer(v.(string))
	}
	if v, ok := d.GetOk("from"); ok {
		from, err := time.Parse(time.RFC3339, v.(string))
		if err != nil {
			return diag.FromErr(err)
		}
		i.From = &from
	}
	if v, ok := d.GetOk("to"); ok {
		to, err := time.Parse(time.RFC3339, v.(string))
		if err != nil {
			return diag.FromErr(err)
		}
		i.To = &to
	}

	all, err := session.List(ctx, conn, &i)
	if err != nil {
		return diag.Errorf("error fetching AI Runtime Control sessions: %s", err)
	}

	hashBase, _ := json.Marshal(all)
	d.SetId(strconv.Itoa(hashcode.String(string(hashBase))))

	if err := d.Set("sessions", flattenAIRuntimeControlSessions(all)); err != nil {
		return diag.Errorf("error setting sessions: %s", err)
	}
	if err := d.Set("total", len(all)); err != nil {
		return diag.Errorf("error setting total: %s", err)
	}

	return nil
}

func flattenAIRuntimeControlSessions(remoteState []session.Session) []map[string]any {
	result := make([]map[string]any, len(remoteState))

	for i, s := range remoteState {
		result[i] = map[string]any{
			"id":               s.ID,
			"virtual_key_id":   s.VirtualKeyID,
			"virtual_key_name": s.VirtualKeyName,
			"model":            s.Model,
			"provider":         s.Provider,
			"requests":         s.Requests,
			"input_tokens":     s.InputTokens,
			"output_tokens":    s.OutputTokens,
			"created_at":       s.CreatedAt,
			"updated_at":       s.UpdatedAt,
			"logs":             flattenAIRuntimeControlSessionLogs(s.Logs),
		}
	}

	return result
}

func flattenAIRuntimeControlSessionLogs(remoteState []session.Log) []map[string]any {
	result := make([]map[string]any, len(remoteState))

	for i, l := range remoteState {
		attrs := make(map[string]string, len(l.Attrs))
		for k, v := range l.Attrs {
			if s, ok := v.(string); ok {
				attrs[k] = s
				continue
			}
			// TypeMap only holds strings, so anything structured is encoded.
			encoded, err := json.Marshal(v)
			if err != nil {
				continue
			}
			attrs[k] = string(encoded)
		}

		result[i] = map[string]any{
			"request":  l.Request,
			"response": l.Response,
			"attrs":    attrs,
		}
	}

	return result
}
